# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/namespace.json
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    app.kubernetes.io/part-of: backup
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
