---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-external-dns-cloudflare
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.7.10
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bitnami-external-dns-cloudflare
  upgrade:
    crds: CreateReplace
  values:
    provider: cloudflare
    registry: txt
    txtOwnerId: external-dns-cloudflare
    policy: sync
    interval: 1m
    logLevel: info
    sources:
      - service
      - ingress
      - gateway-httproute
    domainFilters:
      - example.com
    cloudflare:
      apiTokenExistingSecret: cloudflare-api-token
      proxied: false
      zoneId: REPLACE_WITH_CLOUDFLARE_ZONE_ID
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
    podSecurityContext:
      fsGroup: 1001
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
