---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns
resources:
- namespace.yaml
- bind.yaml
- external-dns-cloudflare.yaml
- external-dns-rfc2136.yaml
