---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns
resources:
- namespace.yaml
- secrets.yaml
- helm-repository.yaml
- external-dns-adguard.yaml