---
apiVersion: v1
kind: Secret
metadata:
  name: adguard-configuration
  namespace: dns
type: Opaque
stringData:
  url: ${ADGUARD_HOME_URL}
  user: ${ADGUARD_HOME_USERNAME}
  password: ${ADGUARD_HOME_PASSWORD}
