# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: purko
  namespace: operators-system
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.0
  url: oci://ghcr.io/purko-io/purko
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: purko
  namespace: operators-system
spec:
  interval: 1h
  targetNamespace: purko-system
  chartRef:
    kind: OCIRepository
    name: purko
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    namespace: purko-system
    dashboard:
      enabled: false
    operator:
      history:
        enabled: false
    starterAgents:
      enabled: false
    presets: []
    triggerRules: []
