---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.28.1@sha256:d93542d68764b2eed5d762d95cbbb94791276817f02bf46274239eaeeef84f1b
  replicas: 1
  args:
  - "--default_lua_flags=allow-undeclared-keys"
  resources:
    limits:
      cpu: 100m
      memory: 384Mi
