---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      # Server
      server:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
            envFrom:
            - secretRef:
                name: immich-config
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                cpu: 1000m
                memory: 1Gi

      # # Machine Learning
      machine-learning:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.4.1@sha256:b3deefd1826f113824e9d7bc30d905e7f823535887d03f869330946b6db3b44a
            envFrom:
            - secretRef:
                name: immich-config
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 2Gi
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"

      # Background Services
      immich-microservices:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
            envFrom:
            - secretRef:
                name: immich-config
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 4Gi

    # Services
    service:
      server:
        enabled: true
        controller: server
        ports:
          http:
            port: 2283
      machine-learning:
        enabled: true
        controller: machine-learning
        ports:
          http:
            port: 3003

    # HTTP Route
    route:
      app:
        enabled: true
        kind: HTTPRoute
        hostnames: [ "photos.${CLUSTER_DOMAIN}" ]
        parentRefs:
          - name: external
            namespace: gateway

    persistence:
      library:
        enabled: true
        existingClaim: photos-pool
        globalMounts:
        - path: /usr/src/app/upload
      geocoding-dump:
        enabled: true
        type: emptyDir
        globalMounts:
        - path: /usr/src/app/.reverse-geocoding-dump
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
        - path: /cache
      transformers-cache:
        enabled: true
        type: emptyDir
        globalMounts:
        - path: /usr/src/app/.transformers_cache
