apiVersion: v1
kind: Secret
metadata:
    name: routine-github-app-key
    namespace: automation
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:JwHsAabLhXs1qMH8mEnEbubQuF82rzrsFWLdYa8ootTYjEKL4cjrcUG8getSxnjJq7NSd6rUt+OGs/liIN9DB/lxWjaRUXYzd/kpTBA7xIoEHmtMTUIxs2T5++e4QAV8k+O/1jdpsTxWxEL8bvpzNyOabPTQnL5HuTjGbj4Okd4XJPBrcPlhzAKl2FPZD9cXMEffFoxVKRaSOAn/cI34PL8QJtskrOWSIb9xAkXm/SQpM52wfdi225MQ7pPmujKAXWnjA13rBKD8t5BLl1Q3dIxhUEhPqBrdPrY3RMWtVbmsrp5GF/IhB3hbcwX07WxMjVjE2V3yzb/C1n9xWI74uC4TztPqm+Sv1/TxcGbeAANpNXgK2qu7py6EU7E1QYiqWf2LelrSoayjsNsUd+5PGC+YP9A05dbHe/oEt1Rb7AdA6Op7oevgiQMX3zXCqU+s00EH/bRhUjs2z20aAJqdbpBpz/baeG+2Hj824Y0G6GiUoEXOqx/uIQFC0IfadI7Rvy0eKOZKBBJ3nSffBfo1AEXtwYw3q5tpm7ZQJ4iXxvyUsBfJAv2srDYpD6c8tvyufaA1+wsRj/LscIkTgpIqb0QshV6sMAvWVldjIArcmlFE2qp8ig7AyTvIV5Dcj8F6KK8jGK8IUWA51ol4fgQH9q/V0gkiKXEtqLqAg3i5GApY0SAwr+2RH1ntuSOO9C9WYvkkY9j3QoR8Ds9lt9iaFarBzgd2OfRlsIgq+XE9KyzcY6oRzBdEnj4+XJZCtmg1oLb46OFXaxq7laisTmDC3idyW1PCY9nw9cgYaE6FMSbyQnpf2TM77GOX8eMARGILeIAl/96hydvBtbOKjFsWRBuM1lwtdWZOb4ZKgcFvIR9RG3gUKXk0NTn34zQMKD19AwGBxJWZr7NAQjx4CBTHUjmBJIeP8XvcIx0IOk4DMfqJqYfMA0ok1go/b1mqvo9KryfiaZhppsu/RwoGy22HDl1KXu8faVl42vhSxpDsEKAboP/GLabr0ATnsFN3vdzo2dAZrLKYbYNDHwkKJPkTZ84+PQWXZ8YY5xT8MU7i6/tClnF8zsfVUHmHtW8Lnan9r5FxGZMiRH+6xz/3rakaRfzvZeKAMikBYpGlfxPZ/X7MhGi9ZPnzGgM9EQoKb7M+rBGis7Ruj6zxERlxOTfGL3TEt+3Bq9PsvJgPm6qWN7dViA+ETCdSEFgdQdAxsU76O78zXA9tYZFPo94EXZr/ceGdZyddbsGC/siQe7dn/F4vImOF7z7VSAzkipoLqbug98J5QnZW6e5D5yHeXX8y+E2gyr2YVu0LxIeuk1stt6iyPiYx1l0BQoLjSGqpYiyvAeM9/npzJTEG/efpcin61wO8L6/H3BFWL8t85pN1LW0Pjiw4uUX6XYNlJrfts/8YGrudrsFu5FU2Q2/pUWngYdGFjoGj3T7oc+pkdG33xEnjYlHlzZMqots3Yt1MGAhwrNd51JJU27seIJQQVdr+KAPbZALnucK2bT7QObOER9hMhl/ikGbEbY8/G5vtPFslBMahWu+1kL/lU0CNZ/vliL+6sgaeM/3eyUHLzzUOGL+d5TbgANAB89mSIzBriUfLLJ1s/T8MjgZ+2QpMhN0c+WQrfFBumGWcopuonwP67DDYuv1vch1ZH5i06AXt495nSmpqT/hAAsP5zLT2VXXnbcH74n/eOAweY1XMuj7vuwwTaEcIby20kQ7dsvdqQZaiTc5cm+Jqr2qpDNRuf2jI15paRM1YZ3wFQUlBoscswOWhKB3ZCX/VGHELiva69vWGnUrScmxnu69TYFrIIKVmCYZe3KEbJZya89dTY5XeyLfAP4Ionc0yx1RpRwSKZ341lJzXmVSBAe9JS5wZBchLZX6kqfR2wtpKofajXyOsdKirjtjRs7yuBBll/9idQHBjDHZiuEVayutg+UtPqTaw4y2dqZZ5UGK4iUYGni6RZfTqdvDKf9DinX5y7/fhWwo10gZdFbg1ho1k6UQQK3mFnSKE5HAcUOZNQdGGB9Qc5zNPJJ/eskmo+1KCJqvtGql3xOMx9fJIeRKRUbTDG9BItjdS/VO9VOhin/M7H0prmTnRU42xlS0mEFe7UKIuXFdpc0hpXDCLIUSFGB+dD83E14GiOJ3eZX4FJbOrXK/ve+n9URTuYZ6HlFRrCTbvsxFlisiftfvMANu952Hb65xNLlA0B1qHjZutpgfEaMhVopu0I0KQuST68VsCIgUG1hU=,iv:Ptbiwq1QdfNCPs1CkXB7RtgEt2f+yhIdVcD1FJtrtNI=,tag:ahpsgZRLuKYzXMbYeuCIqg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T21:08:54Z"
    mac: ENC[AES256_GCM,data:gwUjyFG5y6QfdN5RWiHS32MjsohU6hCs9Lm6bF55S37c4PpV5hb6tWBuGgxbZe/H7Peb7nwBVcmRtNE61nxvyZJaJ2CW8HTbLNj9MOCrjvXJ5et/FDCQS7QIxoZUzhQJU+hTNWSezK3+DwANHALlw2P2OTIZWPcAstwq5cGZmnM=,iv:Qo9EgO9I8VSXIegAb42R+w+2NHqsK8fLUi3xYwFDZRU=,tag:T8PP1B8F7Oy86UtMDKYalw==,type:str]
    pgp:
        - created_at: "2026-07-25T21:08:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DK2T0oPsKQSoSAQdATOfN9mqhW8EhhD2OWBcq9FkVfSejdaiFNvy8yP9WlHMw
            amQNOGDtp6STocW2rX4EYMxfYZrxSqbEKA2tOgqkaCFss7ZKHoTgwkMd+k+AdCes
            0l4BRhie6Z7IIGiFXlOMmC51yneCp+HC8HbBv/tl43a3kUAWXRZjWmVVxMSQ1WYc
            m6QMoWLV/l2sX/NAUXD3YlY791tj9Gu1JDHvjwsCGjFMn1lBbAsmTWsqHuw7JUrT
            =6dbD
            -----END PGP MESSAGE-----
          fp: "0x98C3A69E6747EA68"
        - created_at: "2026-07-25T21:08:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DiZ7E0TI8O2gSAQdA7a6OsENI0jPvTUVesToHl/TdZlWnyu5UytLLljel7zQw
            o2fKJofLFzVfHSf3Wg9aIPv47QM2Q8LDix5vF/KMo7SuAio4z60gKvY1A7B5T6ZQ
            0l4B3Y/++7C4zVBkTgyiP9emvZy3Q3QU2tbDTMkHdOhNMM4yRuZgQI7bUQRl4fsG
            7wExEp4lSz/Ub2++Y16zuxdN89mRDMwETPsv9znq4qNpFntSypa7XSdNmdhqZ0jy
            =vBi/
            -----END PGP MESSAGE-----
          fp: "0x4B9C178B49228EFD"
    version: 3.13.0
