{
 "title": "blocky",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "blocky_url", "label": "blocky API URL", "query": "${VAR_BLOCKY_URL}" }
  ]
 },
 "panels": [
  {
   "title": "Blocking status",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "content": "<style>\n\n.blocky_btn {\n    border: none;\n  cursor: pointer; \n    padding: 12px;\n  font-size: 16px;\n  min-width: 100px\n}\n\n.blocky_greenbtn { \n  background-color: #4CAF50;\n  color: white;\n}\n\n.blocky_redbtn { \n  background-color: #AF504C;\n  color: white;\n}\n\n\n.blocky_alert {\n  font-size: 14px\n}\n</style>\n<div class=\"blocky_alert blocky_alert-warning fade in\">\n  <a href=\"#\" class=\"close\" data-dismiss=\"blocky_alert\" aria-label=\"close\" style=\"text-decoration:none\">&times;</a>Done!\n</div>\n<div>\n   <button class=\"blocky_btn blocky_greenbtn\" onclick=\"blocky_status_enable()\">On</button>\n   <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable5m()\">Off 5m</button>\n   <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable30m()\">Off 30m</button>\n<div>\n\n\n<script type=\"text/javascript\">\n\nfunction blocky_status_disable() {\n  blocky_status_switch(false, 0)\n}\n\nfunction blocky_status_disable5m() {\n  blocky_status_switch(false, 5*60)\n}\n\nfunction blocky_status_disable30m() {\n  blocky_status_switch(false, 30*60)\n}\n\nfunction blocky_status_enable() {\n  blocky_status_switch(true, 0)\n}\n\nfunction blocky_status_switch(enable, duration) {\n  var url = '$blocky_url';\n  op = enable ? 'enable' : 'disable?duration='+duration+\"s\"\n  $.get(url + '/api/blocking/'+op, function(data) {\n    showAlert()\n  })\n   .fail(function() {\n    alert( \"error\" );\n  })\n}\n\nvar showAlert = function() {\n\t// first show the alert\n  $('.blocky_alert').show().fadeTo(500, 1);\n  \n  // Now set a timeout to hide it\n  window.setTimeout(function() {\n    $(\".blocky_alert\").fadeTo(500, 0).slideUp(500, function() {\n      $(this).hide();\n    });\n  }, 3000);\n}\n\n// start with the alert hidden\n$('.blocky_alert').hide();\n\n</script>"
  },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "blocky_blocking_enabled" }
   ]
  },
  {
   "title": "Error count 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(blocky_error_total[24h]))"
    }
   ]
  },
  {
   "title": "Queries blocked 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total{response_type=\"BLOCKED\"}[24h])) / sum(increase(blocky_query_total[24h])) "
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(blocky_query_total[5m])) * 60",
     "legendFormat": "avg requests / min"
    }
   ]
  },
  {
   "title": "Avg response time (all queries) 1h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_sum[1h])) / sum(increase(blocky_request_duration_ms_count[1h]))"
    }
   ]
  },
  {
   "title": "Query Count Total 24h",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_query_total[24h]))) "
    }
   ]
  },
  {
   "title": "Blacklist entries total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(blocky_blacklist_cache) / sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=\"blocky\"})/sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "request duration (upstream)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}[24h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Reasons",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sort_desc(sum by (reason) (ceil(increase(blocky_response_total[24h]))))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Query per Client",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total[24h]))))",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Query by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sort_desc(sum by (type) (ceil(increase(blocky_query_total[24h]))))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Blacklist by group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, blocky_blacklist_cache) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Response Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sort_desc(sum by (response_type) (ceil(increase(blocky_response_total[24h]))))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sort_desc(sum by (response_code) (ceil(increase(blocky_response_total[24h]))))",
     "legendFormat": "{{response_code}}"
    }
   ]
  }
 ]
}