# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: forgejo-runner-registration
  namespace: forgejo-runner
stringData:
  uuid: ${FORGEJO_RUNNER_UUID}
  token: ${FORGEJO_RUNNER_TOKEN}
