# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- forgejo.yaml
- forgejo-runner.yaml
- forgejo-runner-secret.yaml
- forgejo-runner-repo.yaml
